name: "🐛 Launcher Bug Report"
description: Create a new ticket for a Launcher bug.
title: "🐛 [Launcher] - <title>"
labels: [
  "platform: Launcher",
  "type: Bug"
]
body:
  # Description
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true

  # Reproduction steps
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true

  # Screenshots
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false

  # Operating Systems
  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      description: What is the impacted environment?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false